name: Python CI

on:
  workflow_dispatch:

  schedule:
    - cron: "0 8 * * 1-5"

permissions:
  id-token: write
  contents: read

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/599954354904/locations/global/workloadIdentityPools/github-actions/providers/github'
          service_account: 'market-lab-github-actions@backtest-510311.iam.gserviceaccount.com'

      - name: Run Python
        env:
          KIS_APP_KEY: ${{ secrets.KIS_APP_KEY }}
          KIS_APP_SECRET: ${{ secrets.KIS_APP_SECRET }}
        run: |
          python -m src.main